### ISSUE TITLE
Failures on g++ 4.8 / clang 3.9 on Travis

### ISSUE THREAD

**Issue by pdimov** [boostorg/log#43]
See https://travis-ci.org/boostorg/boost/builds/292271102

```
testing.capture-output bin.v2/libs/log/test/form_max_size_decor.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/form_max_size_decor.run
====== BEGIN OUTPUT ======
Running 3 test cases...
Left: "При�"
Right: "При"
libs/log/test/run/form_max_size_decor.cpp(163): error: in "character_boundary_maintenance": check equal_strings(strm1.str(), strm2.str()) has failed
Left: "П�>>>"
Right: "П>>>"
libs/log/test/run/form_max_size_decor.cpp(175): error: in "character_boundary_maintenance": check equal_strings(strm1.str(), strm2.str()) has failed
*** 2 failures are detected in the test module "form_max_size_decor"
EXIT STATUS: 201
====== END OUTPUT ======
```

https://travis-ci.org/boostorg/boost/jobs/292271110#L2500
https://travis-ci.org/boostorg/boost/jobs/292271111#L2615

**Comment by pdimov** [comment]
Same on Appveyor.

https://ci.appveyor.com/project/boostorg/boost/build/1.0.4213-develop

**Comment by Lastique** [comment]
This is a bug in Boost.Detail introduced in https://github.com/boostorg/detail/commit/b47fccb4a4e7fb32b74d03f6f80250bc2cafe501 and fixed in https://github.com/boostorg/detail/commit/aee87734a8474f4ffd5047845a3dd9bbabc74418.

**Comment by pdimov** [comment]
We should probably add a test for that.

**Comment by Lastique** [comment]
C++11 `override` for those methods would be even better. We need `BOOST_OVERRIDE` in Boost.Config.

**Comment by pdimov** [comment]
Does the existing https://github.com/boostorg/detail/blob/develop/test/test_utf8_codecvt.cpp cover that?

**Comment by pdimov** [comment]
`override` won't work, I think, because the point here is that we don't know which virtual we have, the standard or the non-standard one, so we have to override both.

**Comment by Lastique** [comment]
I believe, the non-standard override is not the right way to do this. There should be just one override marked with `override` and its argument should be modified specifically for the compiler that requires that.

**Comment by Lastique** [comment]
> Does the existing https://github.com/boostorg/detail/blob/develop/test/test_utf8_codecvt.cpp cover that?

I can see it calls `length()` and test the result but apparently that didn't reveal the problem. I think that's because the default implementation of `do_length()` just does something similar to `strlen`, which returns the same result that the test expects. In other words, the default implementation does not detect UTF-8 character boundaries, which Boost.Log requires and tests for.

**Comment by pdimov** [comment]
> There should be just one override marked with  override  and its argument should be modified specifically for the compiler that requires that.

The problem, if I recall, is that we either didn't know what compilers (actually standard libraries) require it, or that it wasn't possible to detect them.

**Comment by Lastique** [comment]
IMHO, it's better to write the code as the standard requires and let everyone affected complain. Then add compiler checks on case-by-case basis.


BTW, I've updated the codecvt test.

**Comment by pdimov** [comment]
That's how it was. We had endless problems.

**Comment by Lastique** [comment]
Boost.Locale has the same problem and defines `BOOST_LOCALE_DO_LENGTH_MBSTATE_CONST` for that.

https://github.com/boostorg/locale/blob/develop/include/boost/locale/generic_codecvt.hpp#L28

That doesn't look that scary at all. Of course, there may be other compilers not supported by Boost.Locale but really, how many are there?

**Comment by pdimov** [comment]
At the moment, probably not that very many. In the past,

https://github.com/boostorg/detail/commit/5367f6459d7ab55892c1ea67267ac0592c19686e#diff-211637c4197986a9bbdb9506133b746e

from a quick sampling.

But do whatever, I don't care. I don't use it, it won't break any of my code. :-)

**Comment by pdimov** [comment]
More history: https://github.com/boostorg/detail/commit/eb6208f69ac85ceaa0bd13e050476d519d8e89fd#diff-211637c4197986a9bbdb9506133b746e

**Comment by Lastique** [comment]
Thanks for the links. The second one basically amounts to what Boost.Locale does - a workaround for MSVC, one compiler. (The first one is backwards - it defaults to `const` and "works around" compilers that correctly don't have `const`; which is probably the reason why every compiler except MSVC appeared "broken".)

**Comment by pdimov** [comment]
The problem is that the overload does have `const` in C++98, removed in C++03. The other problem was that Dinkumware was used much more widely in the past, it wasn't just MSVC. The third problem is that changing the overload silently breaks code (it still compiles but stops overriding), so I suspect standard libraries took their time in fixing it. Nowadays that's probably only of historical relevance. But it wasn't not as simple as "oh MSVC was broken, what else is news". The standard was broken.
